/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nvqdrhtzulypdswrtozi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52cWRyaHR6dWx5cGRzd3J0b3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMTMyNjYsImV4cCI6MjA3NDU4OTI2Nn0.4EKxhu3SV-Ba1FL2-jAv13V_kkAAdJxa_ijgzHoRBDc"